title: Hung Vi Tourist
description: >-
  Hùng Vĩ Tourist – đồng hành cùng bạn trên mọi hành trình. 
  Dịch vụ làm VISA nhanh chóng, đặt vé máy bay giá tốt, tour du lịch đa dạng, uy tín và chuyên nghiệp.
starting_year: 2025
url: "https://hungvitourist.vn"
baseurl: ""
navbar-links:
  PostNews: # Tin tức & Bài viết
    url: /post-news
    children:
      - 🎉 Sự Kiện Du Lịch: post-news#event
      - 🏝️ Điểm Đến Hấp Dẫn: post-news#destination
      - 📖 Cẩm Nang Du Lịch: post-news#guide
      - ❤️ Sức Khỏe Khi Du Lịch: post-news#health
      - 📌 Chính Sách & Quy Định: post-news#policy
      - 💡 Mẹo & Bí Quyết Du Lịch: post-news#tips
  Vé Máy Bay: # Vé máy bay
    url: /flights
    children:
      - 🛫 Vé nội địa: flights#domestic
      - 🌏 Vé quốc tế: flights#international
      - 💺 Đặt chỗ & hành lý: flights#booking
  Tour: # Tour du lịch
    url: /tours
    children:
      - 🏞️ Tour trong nước: tours#domestic
      - 🏯 Tour quốc tế: tours#international
      - 🎢 Combo du lịch: tours#combo
      - 🏝️ Du lịch tự túc: tours#freeTravel
      - 🏖️ Danh sách tour: tours/all-tours/
  Hộ chiếu VISA: # Dịch vụ Visa
    url: /visa
    children:
      - 📑 Visa du lịch: visa#travel
      - 💼 Visa công tác: visa#business
      - 🎓 Visa du học: visa#study
      - 🌍 Dịch vụ khác: visa#other
  Hùng Vĩ Service: # Các dịch vụ bổ trợ
    url: /service
    children:
      - 📞 Liên hệ: aboutme
      - 🎓 Tư vấn du lịch: service#consult
      - 🏨 Đặt khách sạn: service#hotel
      - 🚐 Thuê xe du lịch: service#carRental
      - 🛳️ Tour trọn gói: service#packageTour
      - 🎉 Tổ chức sự kiện: service#event
      - 🤝 Hợp tác & đối tác: service#partner
      - 🛒 Dịch vụ khác: service#other

  # 🗝️Tags: tags #thay thế bằng nút tìm kiếm.
avatar: "/img/Picture-HSL/logo-trans.png"
author:
  name: "\U0001F525Hùng Vĩ Tourist\U0001F525"
  rss: true
  email: hungvitourist@gmail.com
  facebook: hungvitourist
  instagram: "@hungvitourist"
  youtube: '@HùngVĩTourist'
  telephone: '0868 549 586'
  tiktok: '@hungvitourist'
company: "CÔNG TY TNHH DỊCH VỤ DU LỊCH HÙNG VĨ"
company_SHORT_NAME: "✨HÙNG VĨ TOURIST✨"
Tax-code: "0315546297"
address-1: "Ấp Bùng Binh, Xã Hưng Thuận, Tỉnh Tây Ninh"
address-2: "-----"
map-address-1: https://maps.app.goo.gl/ASdugnBv1ApFQm738
map-address-2: ------
footer-links-active:
  rss: true
  facebook: true
  email: true
  telephone: true
  youtube: true
  tiktok: true
  map-address-1: false
  map-address-2: false
share-links-active:
  facebook: true
  linkedin: true
#disqus: bang-nguyen-blog
google_analytics: G-97CTZX8FED # Google Analytics Hung Vi Tourist
gtm: GTM-5WMQFC52 # Google Tag Manager Hung Vi Tourist
#fb_app_id: '721347795190980'
excerpt_length: 50
title-separator: '-'
timezone: Asia/Bangkok
markdown: kramdown
highlighter: rouge
paginate: 8
kramdown:
  input: GFM
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      sitemap: true
      comments: true
      social-share: true
      toc: true
  - scope:
      path: ''
    values:
      layout: page
      show-avatar: true
link-tags: true
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - LICENSE
  - README.md
  - Vagrantfile
collections:
  post-news:
    output: true
    permalink: /post-news/:name/   # Tin tức, bài viết
  flights:
    output: true
    permalink: /flights/:name/     # Vé máy bay
  tours:
    output: true
    permalink: /tours/:name/       # Tour du lịch
  visa:
    output: true
    permalink: /visa/:name/        # Dịch vụ Visa
  service:
    output: true
    permalink: /service/:name/     # Các dịch vụ bổ trợ (khách sạn, thuê xe, sự kiện...)

# Optionally, add permalink defaults (for better structure)
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-datapage-generator
  - jekyll-toc

page_gen:
  - data: 'tour_domestic'   # file _data/tour_domestic.csv
    template: 'tourlist'        # _layouts/tour.html
    name: 'ma_tour'         # tên file sẽ là giá trị cột ma_tour
    dir: 'tours/domestic'   # thư mục xuất file
  - data: 'tour_international'
    template: 'tourlist'
    name: 'ma_tour'
    dir: 'tours/international'

# Cấu hình mục lục tự động
toc:
  min_level: 2
  max_level: 4
  ordered: true

feed:
  collections:
    - post-news
    - tours
    - flights
    - visa
    - service